//------------------------------------------------------------------------
//  Scancode.h
//     Esta cabecera define los c¢digos de scan del teclado
//                                                      Juan V. Guerrero
//------------------------------------------------------------------------
#ifndef JVGTOOLS_H
#define JVGTOOLS_H
#define SC_IZQ     0x4B00
#define SC_DER     0x4D00
#define SC_ARRIBA  0x4800
#define SC_ABAJO   0x5000
#define SC_ESC     0x011B
#define SC_ENTER   0x1C0D
#define SC_F1      0x3B00
#define SC_F2      0x3C00
#define SC_F3      0x3D00
#define SC_F4      0x3E00
#define SC_F5      0x3F00
#define SC_F6      0x4000
#define SC_F7      0x4100
#define SC_F8      0x4200
#define SC_F9      0x4300
#define SC_F10     0x4400
#define SC_F11     0x8500
#define SC_F12     0x8600
#define SC_REPAG   0x4900
#define SC_AVPAG   0x5100
#define SC_INS     0x5200
#define SC_SUPR    0x5300
#define SC_INICIO  0x4700
#define SC_FIN     0x4F00
#define SC_TAB     0x0F00
#endif
